{% set name = "langchain-ai21" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_ai21-{{ version }}.tar.gz
  sha256: 16706edd9ba27e9abb18341351ba368b04a29fe6193dac9b476e8238128d50f3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - langchain-core >=0.3.0,<0.4.0
    - langchain-text-splitters >=0.3.0,<0.4.0
    - ai21 >=3.0.0,<4.0.0

test:
  imports:
    - langchain_ai21
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting AI21 and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
