{% set name = "langchain-ai21" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_ai21-{{ version }}.tar.gz
  sha256: b76fd3ded1d0c1f85dbf3311c44784abba6ff2053a3bc60b090b0f368a4b097b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<4.0
    - langchain-core >=0.3.0,<0.4.0
    - langchain-text-splitters >=0.3.0,<0.4.0
    - ai21 >=3.0.0,<4.0.0

test:
  imports:
    - langchain_ai21
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting AI21 and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
