{% set name = "langchain-ai21" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_ai21-{{ version }}.tar.gz
  sha256: 50bce9beb6da3b31526a73790e13873c79ceb251e271355b9161c6ca1f7685bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<4.0
    - langchain-core >=0.2.4,<0.3.0
    - langchain-text-splitters >=0.2.0,<0.3.0
    - ai21 >=2.4.1,<3.0.0

test:
  imports:
    - langchain_ai21
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting AI21 and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
